examen2/api/urls.py
from django.urls import path
from api import views

app_name = "api"
urlpatterns = [
    
]

examen2/core/urls.py
from core import views
from django.urls import path

from .models import *

app_name = "core"
urlpatterns = [
    
    #Propietario
    path('lista/propietario/',views.Propietarios.as_view(), name="propietarios"),
    path('create/propietario/',views.CreatePropietario.as_view(), name="create4"),
    path('update/propietario/<int:pk>/', views.UpdatePropietario.as_view(), name= "update4"),
    path('delete/propietario/<int:pk>/', views.DeletePropietario.as_view(), name= "delete4"),
    
    #Estadio
    path('lista/estadio/',views.Estadios.as_view(), name="estadios"),                               #numeros para mayor facilidad, ademas se acomodo tomando en cuenta los models
    path('create/estadio/',views.CreateEstadio.as_view(), name="create1"),
    path('detail/estadio/<int:pk>/', views.DetailEstadio.as_view(), name= "detail1"),
    path('update/estadio/<int:pk>/', views.UpdateEstadio.as_view(), name= "Update1"),
    path('delete/estadio/<int:pk>/', views.DeleteEstadio.as_view(), name= "delete1"),
    #Equipo
    path('lista/equipo/',views.Equipos.as_view(), name="equipos"),
    path('create/equipo/',views.CreateEquipo.as_view(), name="create2"),
    path('detail/equipo/<int:pk>/', views.DetailEquipo.as_view(), name= "detail2"),
    path('update/equipo/<int:pk>/', views.UpdateEquipo.as_view(), name= "Update2"),
    path('delete/equipo/<int:pk>/', views.DeleteEquipo.as_view(), name= "delete2"),
    #Jugador
    path('lista/jugador/',views.Jugadores.as_view(), name="jugadores"),
    path('create/jugador/',views.CreateJugador.as_view(), name="create3"),
    path('detail/jugador/<int:pk>/', views.DetailJugador.as_view(), name= "detail3"),
    path('update/jugador/<int:pk>/', views.UpdateJugador.as_view(), name= "Update3"),
    path('delete/jugador/<int:pk>/', views.DeleteJugador.as_view(), name= "delete3"),
    
    #Jugadores-equipos
    path('lista/equipos/jugadores/',views.EquiposJugadores.as_view(), name="jugadoresequipo"),
    path('equipos/<int:pk>/', views.Jugadores7.as_view(), name='jugadores7'),
    path('equipos/posicion/<int:pk>/', views.Jugadores8.as_view(), name='jugadores8'),
]

examen2/home/urls.py
from django.urls import path
from home import views

app_name = "home"
urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

examen2/principal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen2/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<style>
  body{
    background-image: url('https://png.pngtree.com/background/20211217/original/pngtree-geometric-pattern-white-gold-minimalist-creative-background-picture-image_1575961.jpg');
    background-repeat: no-repeat ;
    background-size: cover;
    background-attachment: fixed;
  }
</style>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-transparent"> 
    <a class="navbar-brand" href="{% url 'home:index' %}">RAY NFL</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:propietarios' %}">Propietarios</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:estadios' %}">Estadios</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:equipos' %}">Equipos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:jugadores' %}">Jugadores</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:jugadoresequipo' %}">Jugadores por equipos</a>
          </li>
           
        </ul>
    </div>
</nav>
      {% block content %}
      {% endblock content %}
      <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
</body>
</html>