examen2/api/urls.py
from django.urls import path
from api import views

app_name = "api"
urlpatterns = [
    
]

examen2/core/urls.py
from core import views
from django.urls import path

from .models import *

app_name = "core"
urlpatterns = [
    
    #Propietario
    path('lista/propietario/',views.Propietarios.as_view(), name="propietarios"),
    path('create/propietario/',views.CreatePropietario.as_view(), name="create4"),
    path('update/propietario/<int:pk>/', views.UpdatePropietario.as_view(), name= "update4"),
    path('delete/propietario/<int:pk>/', views.DeletePropietario.as_view(), name= "delete4"),
    
    #Estadio
    path('lista/estadio/',views.Estadios.as_view(), name="estadios"),                               #numeros para mayor facilidad, ademas se acomodo tomando en cuenta los models
    path('create/estadio/',views.CreateEstadio.as_view(), name="create1"),
    path('detail/estadio/<int:pk>/', views.DetailEstadio.as_view(), name= "detail1"),
    path('update/estadio/<int:pk>/', views.UpdateEstadio.as_view(), name= "Update1"),
    path('delete/estadio/<int:pk>/', views.DeleteEstadio.as_view(), name= "delete1"),
    #Equipo
    path('lista/equipo/',views.Equipos.as_view(), name="equipos"),
    path('create/equipo/',views.CreateEquipo.as_view(), name="create2"),
    path('detail/equipo/<int:pk>/', views.DetailEquipo.as_view(), name= "detail2"),
    path('update/equipo/<int:pk>/', views.UpdateEquipo.as_view(), name= "Update2"),
    path('delete/equipo/<int:pk>/', views.DeleteEquipo.as_view(), name= "delete2"),
    #Jugador
    path('lista/jugador/',views.Jugadores.as_view(), name="jugadores"),
    path('create/jugador/',views.CreateJugador.as_view(), name="create3"),
    path('detail/jugador/<int:pk>/', views.DetailJugador.as_view(), name= "detail3"),
    path('update/jugador/<int:pk>/', views.UpdateJugador.as_view(), name= "Update3"),
    path('delete/jugador/<int:pk>/', views.DeleteJugador.as_view(), name= "delete3"),
    
    #Jugadores-equipos
    path('lista/equipos/jugadores/',views.EquiposJugadores.as_view(), name="jugadoresequipo"),
    path('equipos/<int:pk>/', views.Jugadores7.as_view(), name='jugadores7'),
    path('equipos/posicion/<int:pk>/', views.Jugadores8.as_view(), name='jugadores8'),
]

examen2/principal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen2/core/models.py
from django.db import models
from django.core.validators import MinValueValidator

class Propietario(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        managed = True
        db_table = 'Propietario'

class Equipo(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100, null=True, blank=True)
    sede = models.CharField(max_length=100, null=True, blank=True)
    propietario = models.ForeignKey(Propietario, on_delete=models.CASCADE)

    class Meta:
        managed = True
        db_table = 'Equipo'

class Jugador(models.Model):
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, null=True, blank=True)
    numero = models.IntegerField(primary_key=True)
    posicion = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        managed = True
        db_table = 'Jugador'

class Estadio(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    capacidad = models.IntegerField(validators=[MinValueValidator(1)], null=True, blank=True)
    tamano = models.IntegerField(validators=[MinValueValidator(1)],null=True, blank=True)
    propietario = models.ForeignKey(Propietario, on_delete=models.CASCADE)

    class Meta:
        managed = True
        db_table = 'Estadio'

examen2/core/forms.py
from django import forms

from .models import *
                                                                #problemas con los private fields, por lo que se opto por dejar uno solo por model
class Propietarioss(forms.ModelForm):
    class Meta:
        model = Propietario
        fields = ['nombre']

class Equiposs(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = ['sede','nombre','propietario']

class Estadioss(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = ['nombre','capacidad','tamano','propietario']
       
class Jugadoress(forms.ModelForm):
    class Meta:
        model = Jugador
        fields = ['equipo', 'nombre', 'numero', 'posicion']

examen2/core/views.py
from django.views.generic import ListView               #se importo por las views 7 y 8
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import *
from .models import *

#Estadio

class Estadios(generic.View):
    template_name = "core/estadios.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Estadio.objects.all()
        self.context = {
            "estadios": queryset  
        }
        return render(request, self.template_name, self.context)



class DetailEstadio(generic.DetailView):
    template_name = "core/detail1.html"
    model = Estadio


class CreateEstadio(generic.CreateView):          #No se puede cambiar nombre del forms propietario por falta de widgets, por los private fields
    template_name = "core/create1.html"
    model = Estadio
    form_class = Estadioss
    success_url = reverse_lazy("core:estadios")


class UpdateEstadio(generic.UpdateView):
    template_name = "core/Update1.html"
    model = Estadio
    form_class = Estadioss
    success_url = reverse_lazy("core:estadios")

class DeleteEstadio(generic.DeleteView):
    template_name = "core/delete1.html"
    model = Estadio
    success_url = reverse_lazy("core:estadios")


#Equipos

class Equipos(generic.View):
    template_name = "core/equipos.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Equipo.objects.all()
        self.context = {
            "equipos": queryset
        }
        return render(request, self.template_name,self.context)
    
class CreateEquipo(generic.CreateView):
    template_name = "core/create2.html"
    model = Equipo
    form_class = Equiposs
    success_url = reverse_lazy("core:equipos")

    def form_valid(self, form):
        
        return super().form_valid(form)


class DetailEquipo(generic.DetailView):
    template_name = "core/detail2.html"
    model = Equipo

class UpdateEquipo(generic.UpdateView):
    template_name = "core/Update2.html"
    model = Equipo
    form_class = Equiposs
    success_url = reverse_lazy("core:equipos")

class DeleteEquipo(generic.DeleteView):
    template_name = "core/delete2.html"
    model = Equipo
    success_url = reverse_lazy("core:equipos")

#Jugadores

class Jugadores(generic.View):
    template_name = "core/jugadores.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Jugador.objects.all()
        self.context = {
            "jugador": queryset
        }
        return render(request, self.template_name,self.context)

class CreateJugador(generic.CreateView):
    template_name = "core/create3.html"
    model = Jugador
    form_class = Jugadoress
    success_url = reverse_lazy("core:jugadores")

class DetailJugador(generic.DetailView):
    template_name = "core/detail3.html"
    model = Jugador

class UpdateJugador(generic.UpdateView):
    template_name = "core/Update3.html"
    model = Jugador
    form_class = Jugadoress
    success_url = reverse_lazy("core:jugadores")

class DeleteJugador(generic.DeleteView):
    template_name = "core/delete3.html"
    model = Jugador
    success_url = reverse_lazy("core:jugadores")
    

#Propietarios

class Propietarios(generic.View):
    template_name = "core/propietarios.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Propietario.objects.all()
        self.context = {
            "propietario": queryset
        }
        return render(request, self.template_name,self.context)

class CreatePropietario(generic.CreateView):
    template_name = "core/create4.html"
    model = Propietario
    form_class = Propietarioss
    success_url = reverse_lazy("core:propietarios")

class UpdatePropietario(generic.UpdateView):
    template_name = "core/update4.html"
    model = Propietario
    form_class = Propietarioss
    success_url = reverse_lazy("core:propietarios")


class DeletePropietario(generic.DeleteView):
    template_name = "core/delete4.html"
    model = Propietario
    success_url = reverse_lazy("core:propietarios")


#jugadores-equipo


class EquiposJugadores(generic.View):
    template_name = "core/jugadoresequipo.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Equipo.objects.all()
        self.context = {
            "equipos": queryset
        }
        return render(request, self.template_name,self.context)

class Jugadores7(ListView):
    model = Jugador
    template_name = 'core/jugadores7.html'
    context_object_name = 'jugadores'

    def get_queryset(self):                 #se obtiene el id de equipo para filtrar
        equipo_id = self.kwargs['pk']  
        return Jugador.objects.filter(equipo_id=equipo_id)

    def get_context_data(self, **kwargs):                #qui es con la url
        context = super().get_context_data(**kwargs)
        equipo_id = self.kwargs['pk']  
        context['equipo_id'] = equipo_id
        return context

class Jugadores8(ListView):
    model = Jugador
    template_name = 'core/jugadores8.html'
    context_object_name = 'jugadores'
                                                    #se realiza lo mismo que con el jugadores7
    def get_queryset(self):
        equipo_id = self.kwargs['pk']  
        return Jugador.objects.filter(equipo_id=equipo_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        equipo_id = self.kwargs['pk'] 
        context['equipo_id'] = equipo_id
        return context

examen2/templates/core/Update1.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar estadio de la NFL
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Aceptar</button>
        <a href="{% url 'core:estadios' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/templates/core/Update2.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar equipo
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar equipo</button>
        <a href="{% url 'core:equipos' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/templates/core/Update3.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar datos de un jugador
{% endblock title %}

{% block content %}
<h1>Actualizar datos del jugador</h1>
<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-primary">Aceptar</button>
  <a href="{% url 'core:jugadores' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

examen2/templates/core/create1.html
{% extends "base/base.html" %}

{% block title %}
Agregar un estadio de futbol
{% endblock title %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-5 offset-md-3">
                <h2>Agregar un estadio de fútbol</h2>
                <form action="" method="post" class="form">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.nombre.label_tag }}                  
                        {{ form.nombre }}
                    </div>
                    <div class="mb-3">
                        {{ form.capacidad.label_tag }}
                        {{ form.capacidad }}
                    </div>
                    <div class="mb-3">
                        {{ form.tamano.label_tag }}
                        {{ form.tamano }}
                    </div>
                    <button type="submit" class="btn btn-success">Aceptar</button>
                    <a href="{% url 'core:estadios' %}" class="btn btn-warning">Cancelar</a>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

examen2/templates/core/create2.html
{% extends "base/base.html" %}

{% block title %}
Agregar un equipo de futbol
{% endblock title %}

{% block content %}

<div class="container">
  <div class="row">
      <div class="col-md-8 offset-md-2">
          <h2>Agregar un equipo de fútbol</h2>
          <form action="" method="post" class="form">
              {% csrf_token %}
              <div class="mb-3">
                  {{ form.sede.label_tag }}                  
                  {{ form.sede }}
              </div>
              <div class="mb-3">
                  {{ form.nombre.label_tag }}
                  {{ form.nombre }}
              </div>
              <div class="mb-3">
                  {{ form.propietario.label_tag }}
                  {{ form.propietario }}
              </div>
              <button type="submit" class="btn btn-success">Aceptar</button>
              <a href="{% url 'core:equipos' %}" class="btn btn-warning">Cancelar</a>
          </form>
      </div>
  </div>
</div>


{% endblock content %}

examen2/templates/core/create3.html
{% extends "base/base.html" %}

{% block title %}
Agregar jugador de futbol
{% endblock title %}

{% block content %}

<div class="container">
  <div class="row">
      <div class="col-md-8 offset-md-2">
          <h2>Agregar un jugador de fútbol</h2>
          <form action="" method="post" class="form">
              {% csrf_token %}
              <div class="mb-3">
                  {{ form.equipo.label_tag }}                  
                  {{ form.equipo }}
              </div>
              <div class="mb-3">
                  {{ form.nombre.label_tag }}
                  {{ form.nombre }}
              </div>
              <div class="mb-3">
                  {{ form.numero.label_tag }}
                  {{ form.numero }}
              </div>
              <div class="mb-3">
                {{ form.posicion.label_tag }}
                {{ form.posicion }}
            </div>
              <button type="submit" class="btn btn-success">Aceptar</button>
              <a href="{% url 'core:equipos' %}" class="btn btn-warning">Cancelar</a>
          </form>
      </div>
  </div>
</div>

{% endblock content %}

examen2/templates/core/create4.html
{% extends "base/base.html" %}

{% block title %}
Agregar propietario
{% endblock title %}

{% block content %}

<div class="container">
  <div class="row">
      <div class="col-md-5 offset-md-3">
          <h2>Agregar un propietario de la NFL</h2>
          <form action="" method="post" class="form">
              {% csrf_token %}
              <div class="mb-3">
                  {{ form.nombre.label_tag }}                  
                  {{ form.nombre }}
              </div>
              <button type="submit" class="btn btn-success">Aceptar</button>
              <a href="{% url 'core:estadios' %}" class="btn btn-warning">Cancelar</a>
          </form>
      </div>
  </div>
</div>

{% endblock content %}

examen2/templates/core/delete1.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar estadio de futbol
{% endblock title %}

{% block content %}

<br>
<p>¿Desea eliminar el estadio de futbol?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Aceptar</button>
  <a href="{% url 'core:estadios' %}" class="btn btn-outline-warning">Cancelar</a>
</form>

{% endblock content %}

examen2/templates/core/delete3.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar jugador de futbol
{% endblock title %}

{% block content %}

<h1>Eliminar jugador</h1>
<p>¿Desea eliminar al jugador de futbol?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Aceptar</button>

  <a href="{% url 'core:jugadores' %}" class="btn btn-outline-warning">Cancelar</a>
</form>


{% endblock content %}

examen2/templates/core/delete4.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar propietario NFL
{% endblock title %}

{% block content %}

<h1>Eliminar jugador</h1>
<p>¿Desea eliminar al propietario NFL?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Aceptar</button>

  <a href="{% url 'core:propietarios' %}" class="btn btn-outline-warning">Cancelar</a>
</form>


{% endblock content %}

examen2/templates/core/detail2.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del equipo de futbol
{% endblock title %}


{% block content %}

<h1>Detalles del equipo</h1>
  <p>Equipo: {{ equipo.nombre }}</p>
  <a href="{% url 'core:equipos' %}" class="btn btn-outline-warning">Regresar</a>
  
  
{% endblock content %}

examen2/templates/core/jugadores.html
{% extends 'base/base.html' %}

{% block title %} Lista de jugadores {% endblock title %}

{% block content %}


    <a href="{% url 'core:create3' %}" class="btn btn-outline-success form-control">Añadir nueva jugador</a>
    <h1>Lista de jugadores</h1>
    <table class="table table-striped table-hover">
        <thead>
            <th>Jugador</th>
            <th></th>
            <th>Acciones</th>
            <th></th>

        </thead>
        <tbody>
            {% for jugador in jugador %}
                <tr>
                    <td>{{ jugador.nombre }}</td>
                    <td><a href="{% url 'core:detail3' jugador.numero %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:Update3' jugador.numero %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{%  url 'core:delete3' jugador.numero %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

examen2/templates/core/jugadores7.html
{% extends 'base/base.html' %}

{% block title %} Lista de jugadores por equipo. {% endblock title %}

{% block content %}

<h1>Jugadores del Equipo (ID: {{ equipo_id }}) - Nombre y Número</h1>
    <ul>
        {% for jugador in jugadores %}
            <li>{{ jugador.nombre }} - {{ jugador.numero }}</li>
        {% endfor %}
    </ul>

{% endblock content %}

examen2/templates/core/propietarios.html
{% extends 'base/base.html' %}

{% block title %} Lista de propietarios {% endblock title %}

{% block content %}


    <a href="{% url 'core:create4' %}" class="btn btn-outline-success form-control">Añadir nuevo propietario</a>
    <h1>Lista de propietarios</h1>
    <table class="table table-striped table-hover">
        <thead>
            <th>Propietarios</th>
            <th>Acciones</th>
            <th></th>

        </thead>
        <tbody>
            {% for propietario in propietario %}
                <tr>
                    <td>{{ propietario.nombre }}</td>
                    <td><a href="{%  url 'core:update4' propietario.id %}" class="btn btn-outline-danger">Actualizar</a></td>
                    <td><a href="{%  url 'core:delete4' propietario.id %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}